# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-06 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(help_text='Descripcion del Paper', verbose_name='Descripcion')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='myfolder/')),
            ],
        ),
    ]
