# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-06 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tb_Papers',
            new_name='Tb_Proyectos',
        ),
    ]
